/**
 * Deterministic playbook file renderer.
 *
 * Spec: tasks/playbooks-spec.md invariant 14 — the save endpoint never
 * trusts client-supplied fileContents. The server is the only producer
 * of the .playbook.ts file body, and renderWorkflowFile() is that
 * single source of truth.
 *
 * This module is intentionally pure — no database, no env, no I/O. It
 * lives under server/lib/workflow/ alongside the validator + templating
 * + hash helpers so the test suite can import it directly without
 * spinning up the wider app graph.
 *
 * Format note: Schemas (initialInputSchema, paramsSchema, formSchema,
 * outputSchema) are emitted as `z.any()` placeholders because the
 * arriving definition is a JSON object — there are no real Zod
 * instances at the boundary, and the runtime validator only checks
 * `outputSchema` for presence (not Zod identity). Studio-authored
 * playbooks rely on the structural definition for shape, not on
 * runtime Zod parsing. Hand-authored playbooks (e.g.
 * server/playbooks/event-creation.playbook.ts) continue to use real
 * Zod schemas; both formats coexist because both are valid TS that
 * imports defineWorkflow.
 */

const DEFINITION_HASH_COMMENT_LINE = (hash: string) => `// @workflow-definition-hash: ${hash}`;

export function renderWorkflowFile(
  definition: Record<string, unknown>,
  hash: string
): string {
  const slug = String(definition.slug ?? '');
  const name = String(definition.name ?? '');
  const description = String(definition.description ?? '');
  const version = Number(definition.version ?? 1);
  const steps = Array.isArray(definition.steps) ? definition.steps : [];

  const lines: string[] = [];
  lines.push('// Generated by Workflow Studio. DO NOT EDIT BY HAND.');
  lines.push('// Re-generate via the Studio UI by editing the definition and re-saving.');
  lines.push('// The hash below is enforced by the save-and-open-pr endpoint and');
  lines.push('// proves this file was rendered deterministically from a validated');
  lines.push('// definition (spec tasks/playbooks-spec.md invariant 14).');
  lines.push(DEFINITION_HASH_COMMENT_LINE(hash));
  lines.push('');
  lines.push("import { defineWorkflow } from '../lib/workflow/defineWorkflow.js';");
  lines.push("import { z } from 'zod';");
  lines.push('');
  lines.push('export default defineWorkflow({');
  lines.push(`  slug: ${JSON.stringify(slug)},`);
  lines.push(`  name: ${JSON.stringify(name)},`);
  lines.push(`  description: ${JSON.stringify(description)},`);
  lines.push(`  version: ${version},`);
  lines.push('  initialInputSchema: z.any(),');
  if (definition.paramsSchema !== undefined) {
    lines.push('  paramsSchema: z.any(),');
  }
  lines.push('  steps: [');
  for (const rawStep of steps) {
    const step = (rawStep ?? {}) as Record<string, unknown>;
    lines.push('    {');
    lines.push(`      id: ${JSON.stringify(String(step.id ?? ''))},`);
    lines.push(`      name: ${JSON.stringify(String(step.name ?? ''))},`);
    if (step.description !== undefined) {
      lines.push(`      description: ${JSON.stringify(String(step.description))},`);
    }
    lines.push(`      type: ${JSON.stringify(String(step.type ?? ''))},`);
    const dependsOn = Array.isArray(step.dependsOn) ? step.dependsOn : [];
    lines.push(`      dependsOn: ${JSON.stringify(dependsOn)},`);
    lines.push(`      sideEffectType: ${JSON.stringify(String(step.sideEffectType ?? ''))},`);
    if (step.humanReviewRequired === true) {
      lines.push('      humanReviewRequired: true,');
    }
    if (step.failurePolicy !== undefined) {
      lines.push(`      failurePolicy: ${JSON.stringify(step.failurePolicy)},`);
    }
    if (step.timeoutSeconds !== undefined) {
      lines.push(`      timeoutSeconds: ${JSON.stringify(step.timeoutSeconds)},`);
    }
    if (step.retryPolicy !== undefined) {
      lines.push(`      retryPolicy: ${JSON.stringify(step.retryPolicy)},`);
    }
    if (step.prompt !== undefined) {
      lines.push(`      prompt: ${JSON.stringify(String(step.prompt))},`);
    }
    if (step.model !== undefined) {
      lines.push(`      model: ${JSON.stringify(String(step.model))},`);
    }
    if (step.agentRef !== undefined) {
      lines.push(`      agentRef: ${JSON.stringify(step.agentRef)},`);
    }
    if (step.agentInputs !== undefined) {
      lines.push(`      agentInputs: ${JSON.stringify(step.agentInputs)},`);
    }
    if (step.actionSlug !== undefined) {
      lines.push(`      actionSlug: ${JSON.stringify(String(step.actionSlug))},`);
    }
    if (step.actionInputs !== undefined) {
      lines.push(`      actionInputs: ${JSON.stringify(step.actionInputs)},`);
    }
    if (step.idempotencyScope !== undefined) {
      lines.push(`      idempotencyScope: ${JSON.stringify(String(step.idempotencyScope))},`);
    }
    if (step.entityKey !== undefined) {
      lines.push(`      entityKey: ${JSON.stringify(String(step.entityKey))},`);
    }
    if (step.firstRunOnly === true) {
      lines.push('      firstRunOnly: true,');
    }
    if (step.final === true) {
      lines.push('      final: true,');
    }
    if (step.referenceBinding !== undefined) {
      lines.push(`      referenceBinding: ${JSON.stringify(step.referenceBinding)},`);
    }
    if (step.decisionPrompt !== undefined) {
      lines.push(`      decisionPrompt: ${JSON.stringify(String(step.decisionPrompt))},`);
    }
    if (step.branches !== undefined) {
      lines.push(`      branches: ${JSON.stringify(step.branches)},`);
    }
    if (step.defaultBranchId !== undefined) {
      lines.push(`      defaultBranchId: ${JSON.stringify(String(step.defaultBranchId))},`);
    }
    if (step.minConfidence !== undefined) {
      lines.push(`      minConfidence: ${JSON.stringify(step.minConfidence)},`);
    }
    // formSchema / outputSchema → z.any() placeholders (see module comment)
    if (step.type === 'user_input' || step.formSchema !== undefined) {
      lines.push('      formSchema: z.any(),');
    }
    if (step.formDescription !== undefined) {
      lines.push(`      formDescription: ${JSON.stringify(String(step.formDescription))},`);
    }
    if (step.approvalPrompt !== undefined) {
      lines.push(`      approvalPrompt: ${JSON.stringify(String(step.approvalPrompt))},`);
    }
    if (step.condition !== undefined) {
      lines.push(`      condition: ${JSON.stringify(step.condition)},`);
    }
    if (step.trueOutput !== undefined) {
      lines.push(`      trueOutput: ${JSON.stringify(step.trueOutput)},`);
    }
    if (step.falseOutput !== undefined) {
      lines.push(`      falseOutput: ${JSON.stringify(step.falseOutput)},`);
    }
    // ── invoke_automation ────────────────────────────────────────────────────
    if (step.automationId !== undefined) {
      lines.push(`      automationId: ${JSON.stringify(String(step.automationId))},`);
    }
    if (step.inputMapping !== undefined) {
      lines.push(`      inputMapping: ${JSON.stringify(step.inputMapping)},`);
    }
    if (step.outputMapping !== undefined) {
      lines.push(`      outputMapping: ${JSON.stringify(step.outputMapping)},`);
    }
    if (step.gateLevel !== undefined) {
      lines.push(`      gateLevel: ${JSON.stringify(step.gateLevel)},`);
    }
    if (step.automationRetryPolicy !== undefined) {
      lines.push(`      automationRetryPolicy: ${JSON.stringify(step.automationRetryPolicy)},`);
    }
    lines.push('      outputSchema: z.any(),');
    lines.push('    },');
  }
  lines.push('  ],');
  if (definition.maxParallelSteps !== undefined) {
    lines.push(`  maxParallelSteps: ${JSON.stringify(definition.maxParallelSteps)},`);
  }
  if (definition.knowledgeBindings !== undefined) {
    lines.push(`  knowledgeBindings: ${JSON.stringify(definition.knowledgeBindings)},`);
  }
  if (definition.portalPresentation !== undefined) {
    lines.push(`  portalPresentation: ${JSON.stringify(definition.portalPresentation)},`);
  }
  if (definition.autoStartOnOnboarding === true) {
    lines.push('  autoStartOnOnboarding: true,');
  }
  lines.push('});');
  lines.push('');
  return lines.join('\n');
}
