import { pgTable, uuid, text, integer, jsonb, timestamp, index } from 'drizzle-orm/pg-core';
import { organisations } from './organisations';
import { subaccounts } from './subaccounts';
import { agents } from './agents';
import { subaccountAgents } from './subaccountAgents';

// ---------------------------------------------------------------------------
// Agent Runs — logs of autonomous agent executions
// ---------------------------------------------------------------------------

export const agentRuns = pgTable(
  'agent_runs',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    organisationId: uuid('organisation_id')
      .notNull()
      .references(() => organisations.id),
    subaccountId: uuid('subaccount_id')
      .notNull()
      .references(() => subaccounts.id),
    agentId: uuid('agent_id')
      .notNull()
      .references(() => agents.id),
    subaccountAgentId: uuid('subaccount_agent_id')
      .notNull()
      .references(() => subaccountAgents.id),

    // How this run was initiated
    runType: text('run_type').notNull().$type<'scheduled' | 'manual' | 'triggered'>(),
    executionMode: text('execution_mode').notNull().default('api').$type<'api' | 'headless'>(),

    // Status tracking
    status: text('status').notNull().default('pending').$type<'pending' | 'running' | 'completed' | 'failed' | 'timeout' | 'cancelled' | 'loop_detected' | 'budget_exceeded'>(),

    // Context & config
    triggerContext: jsonb('trigger_context'), // what initiated the run
    taskId: uuid('task_id'), // if working on a specific board task
    systemPromptSnapshot: text('system_prompt_snapshot'),
    skillsUsed: jsonb('skills_used'), // array of skill slugs available for this run

    // Tool call log — ordered array of { tool, input, output, durationMs }
    toolCallsLog: jsonb('tool_calls_log'),
    totalToolCalls: integer('total_tool_calls').notNull().default(0),

    // Token tracking
    inputTokens: integer('input_tokens').notNull().default(0),
    outputTokens: integer('output_tokens').notNull().default(0),
    totalTokens: integer('total_tokens').notNull().default(0),
    tokenBudget: integer('token_budget').notNull().default(30000),

    // Error tracking
    errorMessage: text('error_message'),
    errorDetail: jsonb('error_detail'),

    // Impact counters
    tasksCreated: integer('tasks_created').notNull().default(0),
    tasksUpdated: integer('tasks_updated').notNull().default(0),
    deliverablesCreated: integer('deliverables_created').notNull().default(0),

    // Replayability: memory state captured at run start
    memoryStateAtStart: text('memory_state_at_start'),

    // Summary of what the agent did (generated by the agent in its final response)
    summary: text('summary'),

    // Context tracking
    systemPromptTokens: integer('system_prompt_tokens').notNull().default(0),

    // Handoff tracking
    handoffDepth: integer('handoff_depth').notNull().default(0),
    parentRunId: uuid('parent_run_id'),

    // Sub-agent tracking
    isSubAgent: integer('is_sub_agent').notNull().default(0), // 0=false, 1=true (pg boolean via int for compat)
    parentSpawnRunId: uuid('parent_spawn_run_id'),

    // Timing
    startedAt: timestamp('started_at'),
    completedAt: timestamp('completed_at'),
    durationMs: integer('duration_ms'),

    createdAt: timestamp('created_at').defaultNow().notNull(),
    updatedAt: timestamp('updated_at').defaultNow().notNull(),
  },
  (table) => ({
    orgIdx: index('agent_runs_org_idx').on(table.organisationId),
    subaccountIdx: index('agent_runs_subaccount_idx').on(table.subaccountId),
    agentIdx: index('agent_runs_agent_idx').on(table.agentId),
    statusIdx: index('agent_runs_status_idx').on(table.status),
    orgStatusIdx: index('agent_runs_org_status_idx').on(table.organisationId, table.status),
    subaccountStatusIdx: index('agent_runs_subaccount_status_idx').on(table.subaccountId, table.status),
    createdAtIdx: index('agent_runs_created_at_idx').on(table.createdAt),
    subaccountAgentIdx: index('agent_runs_subaccount_agent_idx').on(table.subaccountAgentId),
  })
);

export type AgentRun = typeof agentRuns.$inferSelect;
export type NewAgentRun = typeof agentRuns.$inferInsert;
