import { pgTable, uuid, text, integer, boolean, jsonb, timestamp, index, uniqueIndex } from 'drizzle-orm/pg-core';
import { organisations } from './organisations';
import { subaccounts } from './subaccounts';
import { agents } from './agents';
import { subaccountAgents } from './subaccountAgents';

// ---------------------------------------------------------------------------
// Agent Runs — logs of autonomous agent executions
// ---------------------------------------------------------------------------

export const agentRuns = pgTable(
  'agent_runs',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    organisationId: uuid('organisation_id')
      .notNull()
      .references(() => organisations.id),
    subaccountId: uuid('subaccount_id')
      .references(() => subaccounts.id),
    agentId: uuid('agent_id')
      .notNull()
      .references(() => agents.id),
    subaccountAgentId: uuid('subaccount_agent_id')
      .references(() => subaccountAgents.id),

    // Idempotency — prevents duplicate runs on retry
    idempotencyKey: text('idempotency_key'),

    // How this run was initiated
    runType: text('run_type').notNull().$type<'scheduled' | 'manual' | 'triggered'>(),
    executionMode: text('execution_mode').notNull().default('api').$type<'api' | 'headless'>(),

    // Org vs subaccount execution scope (never inferred from nullable fields)
    executionScope: text('execution_scope').notNull().default('subaccount').$type<'subaccount' | 'org'>(),

    // How the run was sourced — explicit for observability and segmentation
    runSource: text('run_source').$type<'scheduler' | 'manual' | 'trigger' | 'handoff' | 'sub_agent' | 'system'>(),

    // Run result classification (success/partial/failed)
    runResultStatus: text('run_result_status').$type<'success' | 'partial' | 'failed'>(),

    // Config snapshot for reproducibility and drift detection
    configSnapshot: jsonb('config_snapshot'),
    configHash: text('config_hash'),
    resolvedSkillSlugs: jsonb('resolved_skill_slugs').$type<string[]>(),
    resolvedLimits: jsonb('resolved_limits'),

    // Status tracking
    status: text('status').notNull().default('pending').$type<'pending' | 'running' | 'completed' | 'failed' | 'timeout' | 'cancelled' | 'loop_detected' | 'budget_exceeded'>(),

    // Context & config
    triggerContext: jsonb('trigger_context'), // what initiated the run
    taskId: uuid('task_id'), // if working on a specific board task
    // systemPromptSnapshot and toolCallsLog moved to agent_run_snapshots (H-5 blob extraction)
    skillsUsed: jsonb('skills_used'), // array of skill slugs available for this run

    totalToolCalls: integer('total_tool_calls').notNull().default(0),

    // Token tracking
    inputTokens: integer('input_tokens').notNull().default(0),
    outputTokens: integer('output_tokens').notNull().default(0),
    totalTokens: integer('total_tokens').notNull().default(0),
    tokenBudget: integer('token_budget').notNull().default(30000),

    // Error tracking
    errorMessage: text('error_message'),
    errorDetail: jsonb('error_detail'),

    // Impact counters
    tasksCreated: integer('tasks_created').notNull().default(0),
    tasksUpdated: integer('tasks_updated').notNull().default(0),
    deliverablesCreated: integer('deliverables_created').notNull().default(0),

    // Replayability: memory state captured at run start
    memoryStateAtStart: text('memory_state_at_start'),

    // Summary of what the agent did (generated by the agent in its final response)
    summary: text('summary'),

    // Context tracking
    systemPromptTokens: integer('system_prompt_tokens').notNull().default(0),

    // Handoff tracking
    handoffDepth: integer('handoff_depth').notNull().default(0),
    parentRunId: uuid('parent_run_id'),

    // Sub-agent tracking — M-10: proper boolean (was integer 0/1)
    isSubAgent: boolean('is_sub_agent').notNull().default(false),
    parentSpawnRunId: uuid('parent_spawn_run_id'),

    // Heartbeat — stale run detection (GSD-2 adoption)
    lastActivityAt: timestamp('last_activity_at', { withTimezone: true }),
    lastToolStartedAt: timestamp('last_tool_started_at', { withTimezone: true }),

    // Timing
    startedAt: timestamp('started_at', { withTimezone: true }),
    completedAt: timestamp('completed_at', { withTimezone: true }),
    durationMs: integer('duration_ms'),

    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => ({
    orgIdx: index('agent_runs_org_idx').on(table.organisationId),
    subaccountIdx: index('agent_runs_subaccount_idx').on(table.subaccountId),
    agentIdx: index('agent_runs_agent_idx').on(table.agentId),
    statusIdx: index('agent_runs_status_idx').on(table.status),
    orgStatusIdx: index('agent_runs_org_status_idx').on(table.organisationId, table.status),
    subaccountStatusIdx: index('agent_runs_subaccount_status_idx').on(table.subaccountId, table.status),
    createdAtIdx: index('agent_runs_created_at_idx').on(table.createdAt),
    subaccountAgentIdx: index('agent_runs_subaccount_agent_idx').on(table.subaccountAgentId),
    // M-4/M-16: missing indexes on FK columns
    taskIdIdx: index('agent_runs_task_id_idx').on(table.taskId),
    parentRunIdIdx: index('agent_runs_parent_run_id_idx').on(table.parentRunId),
    parentSpawnRunIdIdx: index('agent_runs_parent_spawn_run_id_idx').on(table.parentSpawnRunId),
    idempotencyKeyIdx: uniqueIndex('agent_runs_idempotency_key_idx').on(table.idempotencyKey),
    // Stale run cleanup query
    staleRunIdx: index('agent_runs_stale_run_idx').on(table.status, table.lastActivityAt),
  })
);

export type AgentRun = typeof agentRuns.$inferSelect;
export type NewAgentRun = typeof agentRuns.$inferInsert;
