import type { JobName } from '../../config/jobConfig.js';

// Minimum payload for each handler_tested queue.
// The meta-test uses these to invoke handlers in a controlled environment
// (handler=null in v1, so this file seeds the shape for future wiring).
// external_consumer, send_only, and exempt queues are excluded — they have
// no main-app handler to test.
export const JOB_PAYLOAD_FIXTURES: Partial<Record<JobName, Record<string, unknown>>> = {
  'agent-scheduled-run': { subaccountAgentId: 'test-agent', jobId: 'test-job' },
  'agent-org-scheduled-run': { organisationId: 'test-org', agentId: 'test-agent' },
  'agent-handoff-run': { runId: 'test-run', parentRunId: 'test-parent' },
  'agent-triggered-run': { subaccountAgentId: 'test-agent', triggerId: 'test-trigger' },
  'execution-run': { executionId: 'test-exec', runId: 'test-run' },
  'workflow-resume': { workflowRunId: 'test-workflow-run', actionId: 'test-action' },
  'llm-aggregate-update': { idempotencyKey: 'test-key', organisationId: 'test-org' },
  'llm-reconcile-reservations': {},
  'llm-monthly-invoices': { month: '2026-05' },
  'payment-reconciliation': {},
  'stale-run-cleanup': {},
  'maintenance:cleanup-execution-files': {},
  'maintenance:cleanup-budget-reservations': {},
  'maintenance:memory-decay': {},
  'clientpulse:propose-interventions': { churnAssessmentId: 'test-assessment', subaccountId: 'test-sub' },
  'clientpulse:measure-outcomes': {},
  'maintenance:security-events-cleanup': {},
  'agent-run-cleanup': {},
  'priority-feed-cleanup': {},
  'slack-inbound': { teamId: 'T123', eventId: 'evt-test', payload: {} },
  'regression-capture': { reviewItemId: 'test-item', organisationId: 'test-org' },
  'regression-replay-tick': {},
  'llm-clean-old-aggregates': {},
  'maintenance:memory-dedup': {},
  'agent-briefing-update': { agentId: 'test-agent', runId: 'test-run' },
  'memory-context-enrichment': { conversationId: 'test-conv', subaccountId: 'test-sub' },
  'page-integration': { pageId: 'test-page', action: 'sync' },
  'agent-spend-request': { correlationId: 'test-corr', agentRunId: 'test-run' },
  'agent-spend-completion': { correlationId: 'test-corr', agentRunId: 'test-run' },
  'iee-run-completed': { ieeRunId: 'test-iee-run', agentRunId: 'test-run' },
  'skill-analyzer': { jobId: 'test-job', subaccountId: 'test-sub' },
  'workflow-gate-stall-notify': { gateId: 'test-gate', cadence: '24h' },
  'workflow-run-tick': { runId: 'test-workflow-run' },
  'workflow-watchdog': {},
  'workflow-agent-step': { stepRunId: 'test-step', workflowRunId: 'test-workflow-run' },
  'connector-polling-tick': {},
  'connector-polling-sync': { connectionId: 'test-conn', connectorType: 'test' },
  'seat-rollup': {},
  'workspace.migrate-identity': { migrationRequestId: 'test-migration', actorId: 'test-actor' },
  'system-monitor-ingest': { monitorId: 'test-monitor', payload: {} },
  'optimiser-scan': { subaccountId: 'test-sub' },
  'ghl:auto-start-onboarding': { organisationId: 'test-org', subaccountId: 'test-sub' },
  'run:resumeAfterOAuth': { runId: 'test-run' },
  'document:summarise': { documentVersionId: 'test-version' },
  'document:chunk-embed': { documentVersionId: 'test-version' },
  'document:reembed': { organisationId: 'test-org', targetEmbeddingModel: 'test-model' },
  'document:promotion-finalise': { executionFileId: 'test-file', documentVersionId: 'test-version' },
  'support-draft-reconciliation': { draftId: 'test-draft', organisationId: 'test-org' },
  'support-agent-run': { subaccountId: 'test-sub', inboxId: 'test-inbox' },
  'run-artifacts-retention-sweep': {},
  'support-eval-daily': { organisationId: 'test-org' },
  'operator-session-completed': { agentRunId: 'test-run', sessionId: 'test-session' },
  'operator-session-dispatch-next-chain-link': { agentRunId: 'test-run' },
  'operator-session-progressed': { agentRunId: 'test-run', stepCount: 1 },
  'operator-task-profile-gc': {},
  'operator-session-refresh': { connectionId: 'test-conn', refreshBucketEpochSec: 0 },
  'sandbox-harvest-reconciliation': {},
  'sandbox-ceiling-monitor': { sandboxExecutionId: 'test-exec' },
  'sandbox-wall-clock-kill': { sandboxExecutionId: 'test-exec' },
  'sandbox-artefact-purge': { sandboxExecutionId: 'test-exec' },
  'sandbox-telemetry-prune': {},
  'sandbox-logs-prune': {},
  'sandbox-egress-audit-prune': {},
  'maintenance:fast-path-decisions-prune': {},
  'maintenance:rule-auto-deprecate': {},
  'maintenance:fast-path-recalibrate': {},
  'maintenance:llm-ledger-archive': {},
  'maintenance:llm-started-row-sweep': {},
  'maintenance:stale-analyzer-job-sweep': {},
  'maintenance:llm-inflight-history-cleanup': {},
  'maintenance:memory-entry-decay': {},
  'memory-hnsw-reindex': {},
  'memory-blocks-embedding-backfill': {},
  'maintenance:clarification-timeout-sweep': {},
  'maintenance:blocked-run-expiry': {},
  'maintenance:backend-reconciliation': {},
  'maintenance:memory-entry-quality-adjust': {},
  'maintenance:memory-block-synthesis': {},
  'maintenance:bundle-utilization': {},
  'maintenance:portfolio-briefing': {},
  'maintenance:portfolio-digest': {},
  'maintenance:protected-block-divergence': {},
  'maintenance:iee-session-orphan-cleanup': {},
  'maintenance:iee-sessions-compact': {},
  'maintenance:agent-observations-prune': {},
  'maintenance:working-time-rollup-compact': {},
  'maintenance:webhook-replay-nonce-prune': {},
  'maintenance:execution-window-timeout': {},
  'maintenance:approval-expiry': {},
  'maintenance:stripe-agent-reconciliation-poll': {},
  'maintenance:shadow-charge-retention': {},
  'evaluate-all-pending-baselines': {},
  'capture-baseline': { baselineId: 'test-baseline', idempotencyKey: 'test-key' },
  'scorecard:judge': { judgeId: 'test-judge', subaccountId: 'test-sub' },
  'scorecard:judge:forced': { judgeId: 'test-judge', subaccountId: 'test-sub' },
  'bench:execute': { benchRunId: 'test-bench', idempotencyKey: 'test-key' },
  'bench:regression-replay': { benchRunId: 'test-bench', idempotencyKey: 'test-key' },
  'correction:pattern-detect': {},
  'system-monitor-self-check': {},
  'subscription-trial-check': {},
  'orchestrator-from-task': { taskId: 'test-task', idempotencyKey: 'test-key' },
  'ghl:auto-enrol-locations-page': { organisationId: 'test-org', cursor: null },
  'maintenance:oauth-state-cleanup': {},
  'maintenance:rate-limit-cleanup': {},
  'refresh_optimiser_peer_medians': {},
  'refresh_memory_utility_30d': {},
  'iee-browser:daily-cost-rollup': {},
  'workflow-drafts-cleanup': {},
};
