// ---------------------------------------------------------------------------
// MCP Preset Catalogue — curated, tested MCP server definitions shipped with
// the app. Users pick from this catalogue to add integrations.
// ---------------------------------------------------------------------------

export type McpPresetCategory =
  | 'communication'
  | 'crm'
  | 'developer'
  | 'data_search'
  | 'finance'
  | 'files_storage'
  | 'productivity'
  | 'browser'
  | 'google'
  | 'connectors';

export interface McpPreset {
  slug: string;
  name: string;
  description: string;
  category: McpPresetCategory;
  integrationType: 'mcp_server' | 'native_connector';
  connectorType?: string;
  pollIntervalDefault?: number;
  iconUrl?: string;
  transport: 'stdio';
  command: string;
  args: string[];
  credentialProvider?: string;
  requiresConnection: boolean;
  recommendedGateLevel: 'auto' | 'review';
  toolCount: number;
  toolHighlights: string[];
  setupNotes?: string;
}

export const MCP_PRESET_CATEGORY_LABELS: Record<McpPresetCategory, string> = {
  communication: 'Communication',
  crm: 'CRM',
  developer: 'Developer Tools',
  data_search: 'Data & Search',
  finance: 'Finance',
  files_storage: 'Files & Storage',
  productivity: 'Productivity',
  browser: 'Browser',
  google: 'Google Workspace',
  connectors: 'Data Connectors',
};

export const MCP_PRESETS: McpPreset[] = [
  // ── Communication ──────────────────────────────────────────────────────────
  {
    slug: 'gmail',
    name: 'Gmail',
    description: 'Send, read, and search emails via Google Gmail.',
    category: 'communication',
    integrationType: 'mcp_server',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@anthropic/gmail-mcp-server@1.0.0'],
    credentialProvider: 'gmail',
    requiresConnection: true,
    recommendedGateLevel: 'review',
    toolCount: 5,
    toolHighlights: ['send_email', 'read_inbox', 'search_messages', 'read_thread', 'list_labels'],
    setupNotes: 'Requires a Gmail OAuth connection. The subaccount or org must have Gmail connected.',
  },
  {
    slug: 'slack',
    name: 'Slack',
    description: 'Post messages, read channels, and manage conversations in Slack. Also syncs channel activity and engagement metrics for analytics.',
    category: 'communication',
    integrationType: 'mcp_server',
    connectorType: 'slack',
    pollIntervalDefault: 30,
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@anthropic/slack-mcp-server@1.0.0'],
    credentialProvider: 'slack',
    requiresConnection: true,
    recommendedGateLevel: 'auto',
    toolCount: 8,
    toolHighlights: ['post_message', 'list_channels', 'read_channel', 'search_messages', 'data_sync'],
    setupNotes: 'Requires a Slack OAuth connection with chat:write and channels:read scopes.',
  },
  {
    slug: 'discord',
    name: 'Discord',
    description: 'Send messages, manage channels, and read conversations in Discord servers.',
    category: 'communication',
    integrationType: 'mcp_server',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@anthropic/discord-mcp-server@1.0.0'],
    credentialProvider: 'discord',
    requiresConnection: false,
    recommendedGateLevel: 'auto',
    toolCount: 6,
    toolHighlights: ['send_message', 'read_channel', 'list_channels', 'manage_roles'],
    setupNotes: 'Requires DISCORD_BOT_TOKEN in environment variables.',
  },
  {
    slug: 'twilio',
    name: 'Twilio',
    description: 'Send SMS, make voice calls, and manage phone numbers via Twilio.',
    category: 'communication',
    integrationType: 'mcp_server',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@anthropic/twilio-mcp-server@1.0.0'],
    requiresConnection: false,
    recommendedGateLevel: 'review',
    toolCount: 5,
    toolHighlights: ['send_sms', 'make_call', 'list_messages', 'lookup_number'],
    setupNotes: 'Requires TWILIO_ACCOUNT_SID and TWILIO_AUTH_TOKEN in environment variables.',
  },
  {
    slug: 'sendgrid',
    name: 'SendGrid',
    description: 'Send transactional and marketing emails via SendGrid.',
    category: 'communication',
    integrationType: 'mcp_server',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@anthropic/sendgrid-mcp-server@1.0.0'],
    requiresConnection: false,
    recommendedGateLevel: 'review',
    toolCount: 4,
    toolHighlights: ['send_email', 'list_templates', 'get_stats', 'manage_contacts'],
    setupNotes: 'Requires SENDGRID_API_KEY in environment variables.',
  },

  // ── CRM ────────────────────────────────────────────────────────────────────
  {
    slug: 'hubspot',
    name: 'HubSpot',
    description: 'Manage contacts, deals, and companies in HubSpot CRM.',
    category: 'crm',
    integrationType: 'mcp_server',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@anthropic/hubspot-mcp-server@1.0.0'],
    credentialProvider: 'hubspot',
    requiresConnection: true,
    recommendedGateLevel: 'auto',
    toolCount: 12,
    toolHighlights: ['search_contacts', 'create_contact', 'search_deals', 'create_deal', 'list_companies'],
    setupNotes: 'Requires a HubSpot OAuth connection with contacts, content, and deals scopes.',
  },

  // ── Developer ──────────────────────────────────────────────────────────────
  {
    slug: 'github',
    name: 'GitHub',
    description: 'Manage repositories, issues, pull requests, and code on GitHub.',
    category: 'developer',
    integrationType: 'mcp_server',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@anthropic/github-mcp-server@1.0.0'],
    credentialProvider: 'github',
    requiresConnection: true,
    recommendedGateLevel: 'auto',
    toolCount: 12,
    toolHighlights: ['search_repos', 'create_issue', 'list_prs', 'read_file', 'create_pr'],
    setupNotes: 'Requires a GitHub App installation or OAuth connection.',
  },
  {
    slug: 'vercel',
    name: 'Vercel',
    description: 'Manage deployments, domains, and environment variables on Vercel.',
    category: 'developer',
    integrationType: 'mcp_server',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@anthropic/vercel-mcp-server@1.0.0'],
    requiresConnection: false,
    recommendedGateLevel: 'review',
    toolCount: 8,
    toolHighlights: ['list_deployments', 'create_deployment', 'list_domains', 'get_project'],
    setupNotes: 'Requires VERCEL_TOKEN in environment variables.',
  },
  {
    slug: 'cloudflare',
    name: 'Cloudflare',
    description: 'Manage DNS records, workers, and security settings on Cloudflare.',
    category: 'developer',
    integrationType: 'mcp_server',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@anthropic/cloudflare-mcp-server@1.0.0'],
    requiresConnection: false,
    recommendedGateLevel: 'review',
    toolCount: 10,
    toolHighlights: ['list_zones', 'manage_dns', 'deploy_worker', 'purge_cache'],
    setupNotes: 'Requires CLOUDFLARE_API_TOKEN in environment variables.',
  },

  // ── Data & Search ──────────────────────────────────────────────────────────
  {
    slug: 'brave_search',
    name: 'Brave Search',
    description: 'Web search via Brave Search API. No OAuth needed — uses API key.',
    category: 'data_search',
    integrationType: 'mcp_server',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@anthropic/brave-search-mcp-server@1.0.0'],
    requiresConnection: false,
    recommendedGateLevel: 'auto',
    toolCount: 2,
    toolHighlights: ['web_search', 'local_search'],
    setupNotes: 'Requires BRAVE_API_KEY in environment variables. Get one at brave.com/search/api.',
  },
  {
    slug: 'tavily',
    name: 'Tavily',
    description: 'AI-optimised web search with structured results and content extraction.',
    category: 'data_search',
    integrationType: 'mcp_server',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@anthropic/tavily-mcp-server@1.0.0'],
    requiresConnection: false,
    recommendedGateLevel: 'auto',
    toolCount: 3,
    toolHighlights: ['search', 'extract_content', 'search_news'],
    setupNotes: 'Requires TAVILY_API_KEY in environment variables. Get one at tavily.com.',
  },

  // ── Finance ────────────────────────────────────────────────────────────────
  {
    slug: 'stripe',
    name: 'Stripe',
    description: 'Manage payments, customers, and subscriptions via Stripe. Also syncs payment data for analytics.',
    category: 'finance',
    integrationType: 'mcp_server',
    connectorType: 'stripe',
    pollIntervalDefault: 120,
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@anthropic/stripe-mcp-server@1.0.0'],
    credentialProvider: 'stripe',
    requiresConnection: false,
    recommendedGateLevel: 'review',
    toolCount: 8,
    toolHighlights: ['list_customers', 'create_checkout', 'get_balance', 'list_invoices', 'data_sync'],
    setupNotes: 'Requires STRIPE_SECRET_KEY in environment variables.',
  },

  // ── Productivity ───────────────────────────────────────────────────────────
  {
    slug: 'notion',
    name: 'Notion',
    description: 'Read and write pages, databases, and blocks in Notion.',
    category: 'productivity',
    integrationType: 'mcp_server',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@anthropic/notion-mcp-server@1.0.0'],
    requiresConnection: false,
    recommendedGateLevel: 'auto',
    toolCount: 10,
    toolHighlights: ['search', 'read_page', 'create_page', 'query_database', 'update_block'],
    setupNotes: 'Requires NOTION_API_KEY in environment variables. Create an integration at notion.so/my-integrations.',
  },

  // ── Google Workspace ──────────────────────────────────────────────────────
  {
    slug: 'google_calendar',
    name: 'Google Calendar',
    description: 'Create events, check availability, and manage calendars in Google Calendar.',
    category: 'google',
    integrationType: 'mcp_server',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@anthropic/google-calendar-mcp-server@1.0.0'],
    credentialProvider: 'gmail',
    requiresConnection: true,
    recommendedGateLevel: 'auto',
    toolCount: 6,
    toolHighlights: ['create_event', 'list_events', 'check_availability', 'update_event'],
    setupNotes: 'Requires a Google OAuth connection with calendar scopes.',
  },
  {
    slug: 'google_drive',
    name: 'Google Drive',
    description: 'Search, read, and manage files and folders in Google Drive.',
    category: 'google',
    integrationType: 'mcp_server',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@anthropic/google-drive-mcp-server@1.0.0'],
    credentialProvider: 'gmail',
    requiresConnection: true,
    recommendedGateLevel: 'auto',
    toolCount: 8,
    toolHighlights: ['search_files', 'read_file', 'create_file', 'list_folder'],
    setupNotes: 'Requires a Google OAuth connection with drive scopes.',
  },
  {
    slug: 'google_sheets',
    name: 'Google Sheets',
    description: 'Read, write, and manage spreadsheet data in Google Sheets.',
    category: 'google',
    integrationType: 'mcp_server',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@anthropic/google-sheets-mcp-server@1.0.0'],
    credentialProvider: 'gmail',
    requiresConnection: true,
    recommendedGateLevel: 'auto',
    toolCount: 6,
    toolHighlights: ['read_range', 'write_range', 'create_sheet', 'list_sheets'],
    setupNotes: 'Requires a Google OAuth connection with sheets scopes.',
  },
  {
    slug: 'google_docs',
    name: 'Google Docs',
    description: 'Create, read, and edit documents in Google Docs.',
    category: 'google',
    integrationType: 'mcp_server',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@anthropic/google-docs-mcp-server@1.0.0'],
    credentialProvider: 'gmail',
    requiresConnection: true,
    recommendedGateLevel: 'auto',
    toolCount: 5,
    toolHighlights: ['create_document', 'read_document', 'update_document', 'search_docs'],
    setupNotes: 'Requires a Google OAuth connection with docs scopes.',
  },

  // ── Files & Storage ───────────────────────────────────────────────────────
  {
    slug: 'dropbox',
    name: 'Dropbox',
    description: 'Upload, download, search, and manage files in Dropbox.',
    category: 'files_storage',
    integrationType: 'mcp_server',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@anthropic/dropbox-mcp-server@1.0.0'],
    requiresConnection: false,
    recommendedGateLevel: 'auto',
    toolCount: 7,
    toolHighlights: ['upload_file', 'download_file', 'search_files', 'list_folder'],
    setupNotes: 'Requires DROPBOX_ACCESS_TOKEN in environment variables.',
  },

  // ── Data Connectors ─────────────────────────────────────────────────────
  {
    slug: 'connector-ghl',
    name: 'GoHighLevel',
    description: 'Sync contacts, opportunities, conversations, and revenue data from GoHighLevel. Bidirectional — supports creating contacts and triggering campaigns.',
    category: 'connectors',
    integrationType: 'native_connector',
    connectorType: 'ghl',
    transport: 'stdio',
    command: '',
    args: [],
    credentialProvider: 'ghl',
    requiresConnection: true,
    recommendedGateLevel: 'auto',
    pollIntervalDefault: 60,
    toolCount: 0,
    toolHighlights: ['contacts', 'opportunities', 'conversations', 'revenue', 'campaigns'],
    setupNotes: 'Requires GoHighLevel OAuth connection. Syncs data into canonical tables for health scoring and intelligence.',
  },
  {
    slug: 'connector-teamwork',
    name: 'Teamwork Data Sync',
    description: 'Sync projects, tasks, and time tracking data from Teamwork.',
    category: 'connectors',
    integrationType: 'native_connector',
    connectorType: 'teamwork',
    transport: 'stdio',
    command: '',
    args: [],
    requiresConnection: false,
    recommendedGateLevel: 'auto',
    pollIntervalDefault: 60,
    toolCount: 0,
    toolHighlights: ['projects', 'tasks', 'time_entries', 'milestones'],
    setupNotes: 'Requires Teamwork API key. Syncs project data into canonical tables.',
  },

  // ── Finance & Accounting ──────────────────────────────────────────────────
  {
    slug: 'xero',
    name: 'Xero',
    description: 'Manage invoices, contacts, bank transactions, and accounts in Xero.',
    category: 'finance',
    integrationType: 'mcp_server',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@anthropic/xero-mcp-server@1.0.0'],
    requiresConnection: false,
    recommendedGateLevel: 'review',
    toolCount: 8,
    toolHighlights: ['list_invoices', 'create_invoice', 'list_contacts', 'get_accounts'],
    setupNotes: 'Requires XERO_CLIENT_ID and XERO_CLIENT_SECRET in environment variables.',
  },
  {
    slug: 'quickbooks',
    name: 'QuickBooks',
    description: 'Manage customers, invoices, payments, and reports in QuickBooks Online.',
    category: 'finance',
    integrationType: 'mcp_server',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@anthropic/quickbooks-mcp-server@1.0.0'],
    requiresConnection: false,
    recommendedGateLevel: 'review',
    toolCount: 10,
    toolHighlights: ['list_customers', 'create_invoice', 'list_payments', 'run_report'],
    setupNotes: 'Requires QUICKBOOKS_CLIENT_ID, QUICKBOOKS_CLIENT_SECRET, and QUICKBOOKS_REALM_ID in environment variables.',
  },

  // ── Files & Storage ───────────────────────────────────────────────────────
  {
    slug: 'aws_s3',
    name: 'AWS S3',
    description: 'Upload, download, list, and manage objects and buckets in Amazon S3.',
    category: 'files_storage',
    integrationType: 'mcp_server',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@anthropic/s3-mcp-server@1.0.0'],
    requiresConnection: false,
    recommendedGateLevel: 'auto',
    toolCount: 7,
    toolHighlights: ['list_buckets', 'list_objects', 'get_object', 'put_object'],
    setupNotes: 'Requires AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY in environment variables. Optionally set AWS_REGION.',
  },

  // ── CRM ───────────────────────────────────────────────────────────────────
  // ── Browser / Scraping ────────────────────────────────────────────────────
  {
    slug: 'scrapling',
    name: 'Scrapling',
    description: 'Anti-bot web scraping with Cloudflare bypass and stealth browsing.',
    category: 'browser' as McpPresetCategory,
    integrationType: 'mcp_server' as const,
    transport: 'stdio' as const,
    command: 'uvx',
    args: ['scrapling', 'mcp'],
    requiresConnection: false,
    recommendedGateLevel: 'auto' as const,
    toolCount: 10,
    toolHighlights: ['get', 'stealthy_fetch', 'bulk_get', 'open_session'],
    setupNotes: 'Requires Python 3.10+ and uvx. Automatically installs Scrapling and browser binaries on first run.',
  },

  // ── CRM ───────────────────────────────────────────────────────────────────
  {
    slug: 'salesforce',
    name: 'Salesforce',
    description: 'Query records, manage leads, contacts, opportunities, and run reports in Salesforce.',
    category: 'crm',
    integrationType: 'mcp_server',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@anthropic/salesforce-mcp-server@1.0.0'],
    credentialProvider: 'salesforce',
    requiresConnection: false,
    recommendedGateLevel: 'auto',
    toolCount: 12,
    toolHighlights: ['query_records', 'create_lead', 'update_opportunity', 'run_report'],
    setupNotes: 'Requires SALESFORCE_INSTANCE_URL, SALESFORCE_CLIENT_ID, and SALESFORCE_CLIENT_SECRET in environment variables.',
  },
  {
    slug: 'pipedrive',
    name: 'Pipedrive',
    description: 'Manage deals, contacts, activities, and pipelines in Pipedrive CRM.',
    category: 'crm',
    integrationType: 'mcp_server',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@anthropic/pipedrive-mcp-server@1.0.0'],
    requiresConnection: false,
    recommendedGateLevel: 'auto',
    toolCount: 10,
    toolHighlights: ['list_deals', 'create_deal', 'list_contacts', 'list_activities'],
    setupNotes: 'Requires PIPEDRIVE_API_TOKEN in environment variables.',
  },
  {
    slug: 'zoho_crm',
    name: 'Zoho CRM',
    description: 'Manage leads, contacts, deals, and accounts in Zoho CRM.',
    category: 'crm',
    integrationType: 'mcp_server',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@anthropic/zoho-crm-mcp-server@1.0.0'],
    requiresConnection: false,
    recommendedGateLevel: 'auto',
    toolCount: 10,
    toolHighlights: ['search_records', 'create_lead', 'update_deal', 'list_modules'],
    setupNotes: 'Requires ZOHO_CLIENT_ID, ZOHO_CLIENT_SECRET, and ZOHO_REFRESH_TOKEN in environment variables.',
  },
];
