/**
 * Canonical error-code taxonomy.
 *
 * Every `errorCode` string emitted by server routes / services / jobs SHOULD
 * come from this union. The companion gate
 * `scripts/verify-error-code-taxonomy.sh` runs in baseline mode — it records
 * the current count of unaccompanied raw-string callsites in
 * `scripts/guard-baselines.json` and fails only when that count grows.
 *
 * v1 scope (Wave 4 Session I' — CHATGPT-R3-2): the union below enumerates
 * every error code present in the server/ + shared/ tree at the time of
 * authoring (275 distinct codes). Callsites have NOT yet been migrated to
 * import this type — the baseline-style gate prevents NEW raw strings from
 * landing while v2 migrates the existing 422 callsites in batches.
 *
 * v2 follow-up (tasks/todo.md CHATGPT-R3-2-V2): migrate callsites in batches
 * by domain (routes, services, jobs) so each batch is reviewable. Each batch
 * tightens the baseline. Final state: zero raw-string callsites, gate flips
 * from baseline mode to strict mode.
 *
 * Adding a new error code: append it to ERROR_CODES below. The union type
 * picks it up automatically via `typeof`. The gate will then accept the new
 * code at call sites once they migrate to `errorCode satisfies ErrorCode`.
 *
 * Two casing conventions exist in the current set (UPPER_SNAKE and
 * snake_case). v1 captures both as-is — re-casing is out of scope and would
 * be a breaking change for any clients reading these codes. Future work
 * (out of scope for this PR) may introduce an `ErrorCodeNamespace` typedef
 * to group dotted codes like `connection.status_invalid`.
 */

export const ERROR_CODES = [
  'ACTION_NOT_FOUND',
  'AGENCY_ALREADY_INSTALLED',
  'AGENT_MISSING',
  'AGENT_NOT_FOUND',
  'AGENT_NO_OWNER',
  'AGENT_REQUIRED_FOR_SENSITIVE',
  'AGENT_RUN_NOT_FOUND',
  'ARTEFACT_ALREADY_COMPLETED',
  'ARTEFACT_NOT_COMPLETED',
  'ARTEFACT_TARGET_MISSING',
  'AUTH',
  'BASELINE_ARTEFACTS_VERSION_MISMATCH',
  'BASELINE_CAPTURING',
  'BASELINE_NOT_FOUND',
  'BASELINE_SKIP_NOT_PERMITTED',
  'BASELINE_SLUG_CONFLICT',
  'BENCH_COST_CAP_EXCEEDED',
  'BLOCK_NOT_FOUND',
  'BLOCK_STATUS_NOT_ACTIVE',
  'BUDGET_BLOCK_AUDIT_TRAIL_DROPPED',
  'CANONICAL_FILE_MISSING',
  'CLARIFICATION_NOT_PENDING',
  'CLASSIFICATION_PARSE_FAILURE',
  'COMMENT_REQUIRED',
  'CONTENT_CONTAINS_DELIMITER',
  'CONVERSATION_NOT_FOUND',
  'CREDENTIAL_INJECT_FAILED',
  'CRM_UPSTREAM',
  'DECAY_FAILED',
  'DESCRIPTION_TOO_SHORT',
  'DOCUMENT_ALREADY_LINKED',
  'DOCX_UNAVAILABLE',
  'DRAFT_NOT_APPROVED',
  'DRAFT_NOT_FOUND',
  'DRAFT_OWNER_MISMATCH',
  'DRAFT_SEND_IN_FLIGHT',
  'DRIFT_DETECTED',
  'EMBEDDING_PROVIDER_ERROR',
  'ERR',
  'ETAG_MISMATCH',
  'EXECUTION_LOCKED',
  'EXECUTION_LOCK_FRESH',
  'EXECUTION_LOCK_NOT_HELD',
  'EXECUTION_LOCK_NO_START',
  'EXECUTION_LOCK_RELEASED_CONCURRENTLY',
  'FILE_ALREADY_PROMOTED',
  'FILE_NOT_FOUND',
  'FORBIDDEN',
  'GATEWAY',
  'GCAL_API_ERROR',
  'IDEMPOTENCY_KEY_REQUIRED',
  'IDENTITY_KEY_DELETION_BLOCKED',
  'IEE_BROWSER_SETTINGS_CONFLICT',
  'IEE_IDEMPOTENCY_RACE',
  'IEE_RUN_NOT_FOUND',
  'IEE_TASK_REQUIRED',
  'IEE_TASK_TYPE_MISMATCH',
  'INTEGRATION_NOT_CONNECTED',
  'INTERNAL_ERROR',
  'INVALID_ARTEFACT_PAYLOAD',
  'INVALID_BAND',
  'INVALID_BASELINE_SLUG',
  'INVALID_BODY',
  'INVALID_BUDGET',
  'INVALID_CURSOR',
  'INVALID_DUE_DATE',
  'INVALID_FROM',
  'INVALID_INPUT',
  'INVALID_LIMIT',
  'INVALID_LINKED_AGENT',
  'INVALID_METADATA',
  'INVALID_MONTH',
  'INVALID_NAME',
  'INVALID_PATCH',
  'INVALID_PATH',
  'INVALID_PAYLOAD',
  'INVALID_PORTAL_MODE',
  'INVALID_RUNTIME_KEY',
  'INVALID_SCOPE_TIER_COMBINATION',
  'INVALID_TO',
  'INVALID_TOKEN',
  'INVALID_UPDATED_AFTER',
  'INVALID_WINDOW_DAYS',
  'ITEM_CONFLICT',
  'LEAD_COUNT_EXCEEDS_HISTORICAL_HIGH',
  'LEGACY_ERROR',
  'LINK_NOT_FOUND',
  'LOADING_MODE_DEPRECATED',
  'MAMMOTH_UNAVAILABLE',
  'MERGE_CRITICAL_WARNINGS',
  'MISSING_DRAFT_ID',
  'MISSING_OWNER_EMAIL',
  'MISSING_SCHEDULE',
  'MISSING_SUBACCOUNT_AGENT_ID',
  'MISSING_SUBACCOUNT_ID',
  'MONITOR_UNSUPPORTED_FREQUENCY',
  'NETWORK_TIMEOUT',
  'NOT_CLARIFICATION',
  'NOT_FOUND',
  'NOT_PROTECTED_BLOCK',
  'NOT_RESOLVABLE_HERE',
  'NO_OPERATOR_SESSION_CREDENTIAL',
  'NO_SUBACCOUNT',
  'ONBOARDING_INCOMPLETE',
  'OPERATOR_CHAIN_LINK_START_FAILED',
  'OPERATOR_RUN_NOT_FOUND',
  'OPERATOR_SESSION_SUSPENDED',
  'OPTIMISER_SCHEDULE_AGENT_MISSING',
  'ORGANISATION_NOT_FOUND',
  'ORG_NOT_FOUND',
  'OTHER',
  'PAYLOAD_GONE',
  'PROJECT_NOT_FOUND',
  'PROTECTED_MEMORY_BLOCK',
  'PROTECTED_MEMORY_BLOCK_ATTACHMENT',
  'PULSE_ITEM_NOT_FOUND',
  'QUOTA_EXCEEDED',
  'RATE_LIMITED',
  'RECONCILIATION_REQUIRED',
  'RESULT_LOCKED',
  'RESUME_TOKEN_EXPIRED',
  'RUN_NOT_FOUND',
  'SCRAPE_DOMAIN_BLOCKED',
  'SCRAPE_DOMAIN_NOT_ALLOWED',
  'SCRAPE_INVALID_URL',
  'SCRAPE_RATE_LIMITED',
  'SCRAPE_ROBOTS_DISALLOWED',
  'SLACK_API_ERROR',
  'SLACK_DM_OPEN_FAILED',
  'SLUG_CONFLICT',
  'STALE_RESOLVE',
  'SUBACCOUNT_AGENT_NOT_FOUND',
  'SUBACCOUNT_NOT_FOUND',
  'SUGGESTION_UNAVAILABLE',
  'SYSTEM_AGENT_READ_ONLY',
  'TEAMWORK_BAD_GATEWAY',
  'TEST_MANUAL_TRIGGER',
  'TIER12_MISSING_MEMORY_BLOCK_ID',
  'TIER3_WORKSPACE_MEMORY_MISSING',
  'TIMEOUT',
  'TRIGGER_ADD_NOT_SUPPORTED',
  'UNKNOWN_ACTION_TYPE',
  'UNKNOWN_FEATURE_KEY',
  'VALIDATION',
  'VALIDATION_ERROR',
  'VALIDATION_FAILED',
  'WRONG_APPROVER',
  'adapter_error',
  'agent_config_invalid',
  'already_installed',
  'already_provisioning',
  'already_submitted',
  'ambiguous_intent',
  'approver_conflict',
  'artifact_not_found',
  'backfill_requires_org_tx_context',
  'bad_input',
  'base_commit_mismatch',
  'base_version_changed',
  'channel_dispatch_failed',
  'classify_db_failed',
  'classify_invalid_input',
  'classify_llm_failed',
  'concurrent_default_change',
  'concurrent_execute',
  'concurrent_publish',
  'concurrent_update',
  'conflict',
  'connection.status_invalid',
  'connector_connection_error',
  'connector_sync_failed',
  'consent_backfill_already_filled',
  'cost_exceeded',
  'credential_not_found',
  'credential_not_usable',
  'cross_owner_assembler_precondition',
  'cross_subtree_not_permitted',
  'default_grant_failed',
  'delegation_out_of_scope',
  'disclosure_required',
  'duplicate_subscription_label',
  'empty_response',
  'environment_failure',
  'etag_mismatch',
  'execution_failure',
  'file_not_found',
  'forbidden',
  'hierarchy_context_missing',
  'http_403',
  'http_404',
  'idempotency_key_collision_unresolvable',
  'inbox_action_not_applicable',
  'inbox_action_not_implemented',
  'ingest_pipeline_degraded',
  'internal_error',
  'invalid_agent_id',
  'invalid_form_values',
  'invalid_request_source',
  'invalid_slug',
  'invalid_state',
  'invalid_state_transition',
  'invalid_triggering_run_id',
  'job_dlq',
  'last_root_protected',
  'ledger_amount_mismatch',
  'live_call_failed',
  'max_handoff_depth_exceeded',
  'missing_permission',
  'negative_aggregate_clamp',
  'no_active_run_for_task',
  'no_adapter',
  'no_connection',
  'no_prior_consent_use_connect',
  'not_found',
  'not_implemented',
  'not_in_approver_pool',
  'observation_body_too_large',
  'onboarding_slug_not_owed',
  'onboarding_template_not_found',
  'owner_mismatch_transfer_ownership_required',
  'patch_size_exceeded',
  'permission_failure',
  'pinned_version_unavailable',
  'policy_changed',
  'prompt_override_invalid',
  'propose_reply_empty_response',
  'propose_reply_llm_failed',
  'provider_mechanism_not_verified',
  'publish_inconsistent',
  'reconciliation_mismatch',
  'reconciliation_poll_failed',
  'referenceDocument.scope_cross_org',
  'run_gone',
  'run_not_found',
  's3_download_failed',
  's3_signed_url_failed',
  's3_upload_failed',
  'session_already_exists_for_run',
  'skill_analyzer_failed',
  'skill_fail_run',
  'spending_budget_conflict',
  'spending_policy_conflict',
  'step_not_found',
  'stripeAgentWebhook.non_active_connection',
  'stripeAgentWebhook.signature_failure',
  'subaccount_not_found',
  'supersession_cycle_detected',
  'support.draft.scope_mismatch',
  'system_agent_missing',
  'system_ops_org_missing',
  'system_ops_subaccount_missing',
  'template_missing',
  'tenant_mismatch',
  'ticket_not_found',
  'token_encryption_required',
  'triggering_run_not_found',
  'triggering_run_org_mismatch',
  'triggering_run_subaccount_mismatch',
  'unexpected_unique_violation',
  'unknown',
  'unknown_action_type',
  'unknown_code',
  'unknown_type',
  'unsupported_query',
  'validation_error',
  'validation_failed',
  'validation_failure',
  'version_not_found',
  'web_login_config_incomplete',
  'web_login_password_missing',
  'webhook.signature_required',
  'webhook_handler_failed',
  'webhook_ordering_anomaly',
  'worker_error',
  'workflow_context_overflow',
  'workflow_dag_invalid',
  'workflow_stale_version',
  'workflow_studio_pr_disabled',
  'workflow_version_regression',
  'wrong_gate_type',
  // Closed-Loop Skill Improvement — amendment pipeline (spec §9.1, §11, §18)
  'amendment_state_conflict',
  'body_validation_failed',
  'freeze_conflict',
  'invalid_transition',
] as const;

export type ErrorCode = typeof ERROR_CODES[number];

const ERROR_CODE_SET: ReadonlySet<string> = new Set(ERROR_CODES);

/** Type predicate for runtime narrowing at boundaries (route handlers, log shippers). */
export function isErrorCode(value: unknown): value is ErrorCode {
  return typeof value === 'string' && ERROR_CODE_SET.has(value);
}
