/**
 * Regenerates companies/automation-os/automation-os-manifest.json from
 * frontmatter in companies/automation-os/agents/<slug>/AGENTS.md.
 *
 * Usage:
 *   npx tsx scripts/regenerate-company-manifest.ts          # write mode
 *   npx tsx scripts/regenerate-company-manifest.ts --check  # drift-check mode (exit 1 on mismatch)
 *
 * MANIFEST_VERSION is the single-source version string — update here when v7.2 lands.
 * Spec: §4.13 + §12.2.1.
 */

import { readdir, readFile, writeFile } from 'fs/promises';
import { join, resolve } from 'path';

const MANIFEST_VERSION = '7.1.0'; // spec §4.13 + §12.2.1
const MASTER_BRIEF = 'docs/automation-os-system-agents-master-brief-v7.1.md';
const COMPANY_DESCRIPTION =
  'The platform\'s own agent company — a 22-agent team spanning product development, customer operations, growth, finance, back-office operations, and portfolio health.';

const AGENTS_DIR = resolve('companies/automation-os/agents');
const MANIFEST_PATH = resolve('companies/automation-os/automation-os-manifest.json');

function parseFrontmatter(raw: string): Record<string, unknown> {
  const match = raw.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  if (!match) return {};
  const lines = match[1].split('\n');
  const result: Record<string, unknown> = {};
  for (const line of lines) {
    const colon = line.indexOf(':');
    if (colon === -1) continue;
    const key = line.slice(0, colon).trim();
    const val = line.slice(colon + 1).trim();
    if (val === 'null' || val === '~') result[key] = null;
    else if (val === 'true') result[key] = true;
    else if (val === 'false') result[key] = false;
    else if (/^\d+(\.\d+)?$/.test(val)) result[key] = Number(val);
    else result[key] = val.replace(/^['"]|['"]$/g, '');
  }
  return result;
}

async function buildManifest() {
  const slugDirs = await readdir(AGENTS_DIR, { withFileTypes: true });
  const agents: Record<string, unknown>[] = [];

  for (const entry of slugDirs) {
    if (!entry.isDirectory()) continue;
    const agentPath = join(AGENTS_DIR, entry.name, 'AGENTS.md');
    let raw: string;
    try {
      raw = await readFile(agentPath, 'utf8');
    } catch {
      continue;
    }
    const fm = parseFrontmatter(raw);
    const agentEntry: Record<string, unknown> = {
      slug: fm['slug'] ?? entry.name,
      name: fm['name'] ?? entry.name,
      title: fm['title'] ?? null,
      reportsTo: fm['reportsTo'] ?? null,
      model: fm['model'] ?? null,
      schedule: fm['schedule'] ?? null,
      gate: fm['gate'] ?? null,
    };
    if (fm['phase'] !== undefined) agentEntry['phase'] = fm['phase'];
    agents.push(agentEntry);
  }

  // Sort by slug for deterministic output (spec §12.2.1)
  agents.sort((a, b) => String(a['slug']).localeCompare(String(b['slug'])));

  return {
    _comment:
      'INDEX ONLY — generated by scripts/regenerate-company-manifest.ts. Do not hand-edit.',
    parserVersion: '1.0.0',
    company: {
      name: 'Automation OS',
      description: COMPANY_DESCRIPTION,
      slug: 'automation-os',
      schema: 'agentcompanies/v1',
      version: MANIFEST_VERSION,
      sourceOfTruth: 'companies/automation-os/agents/<slug>/AGENTS.md',
      seedScript: 'scripts/seed.ts',
      masterBrief: MASTER_BRIEF,
      agents,
    },
  };
}

async function main() {
  const checkMode = process.argv.includes('--check');
  const manifest = await buildManifest();
  const generated = JSON.stringify(manifest, null, 2) + '\n';

  if (checkMode) {
    let onDisk: string;
    try {
      onDisk = await readFile(MANIFEST_PATH, 'utf8');
    } catch {
      console.error('ERROR: manifest file not found — run without --check to generate it');
      process.exit(1);
    }
    if (onDisk.replace(/\r\n/g, '\n') === generated) {
      console.log('OK: manifest is up to date');
      process.exit(0);
    } else {
      console.error('DRIFT DETECTED: manifest differs from generated output');
      console.error('Run: npx tsx scripts/regenerate-company-manifest.ts');
      process.exit(1);
    }
  } else {
    await writeFile(MANIFEST_PATH, generated, 'utf8');
    console.log(`Written: ${MANIFEST_PATH} (${manifest.company.agents.length} agents, v${MANIFEST_VERSION})`);
  }
}

main().catch(err => { console.error(err); process.exit(1); });
