/**
 * activityServicePure.ts — Pure (no DB / no env) helpers extracted from
 * activityService.ts, exported for unit testing.
 *
 * Task 1.3 — Activity service additive fields + deterministic sort tiebreaker
 * + partial-failure resilience.
 */

// ---------------------------------------------------------------------------
// TriggerType — shared type for both the exported ActivityItem field and the
// pure helper below.  Matches executions.triggerType + the derived values for
// agent_runs.
// ---------------------------------------------------------------------------

export type TriggerType = 'manual' | 'scheduled' | 'webhook' | 'agent' | 'system';

// ---------------------------------------------------------------------------
// mapAgentRunTriggerType — pure derivation of triggerType from the
// agent_runs table columns run_type and run_source.
//
// Rules (Task 1.3 spec §Contract changes):
//   run_type='scheduled'                                       → 'scheduled'
//   run_type='manual'                                          → 'manual'
//   run_type='triggered' AND run_source IN ('sub_agent','handoff') → 'agent'
//   run_type='triggered' AND run_source is anything else       → 'webhook'
//   run_source null: fall back to run_type-only resolution
//     (treat as webhook if triggered)
// ---------------------------------------------------------------------------

export function mapAgentRunTriggerType(
  runType: string,
  runSource: string | null,
): TriggerType | null {
  switch (runType) {
    case 'scheduled':
      return 'scheduled';
    case 'manual':
      return 'manual';
    case 'triggered':
      if (runSource === 'sub_agent' || runSource === 'handoff') return 'agent';
      // null runSource or any other value → treat as webhook
      return 'webhook';
    default:
      return null;
  }
}

// ---------------------------------------------------------------------------
// sortActivityItems — deterministic sort with id DESC tiebreaker.
//
// Accepts a minimal shape (only the fields needed for sorting) so the pure
// tests don't have to construct a full ActivityItem.
// ---------------------------------------------------------------------------

export type SortableItem = {
  id: string;
  status: string;
  severity: string | null;
  createdAt: string;
};

const SEVERITY_ORDER: Record<string, number> = { critical: 0, warning: 1, info: 2 };
const STATUS_ORDER: Record<string, number> = {
  attention_needed: 0,
  failed: 1,
  active: 2,
  completed: 3,
  cancelled: 4,
};

/**
 * Tiebreaker: when two createdAt timestamps are equal, sort by id DESC
 * (lexicographic — UUIDs generated by defaultRandom() are ordered by
 * insertion time, so this gives a stable, consistent secondary ordering).
 */
function idDesc(a: SortableItem, b: SortableItem): number {
  if (a.id > b.id) return -1;
  if (a.id < b.id) return 1;
  return 0;
}

export function sortActivityItems<T extends SortableItem>(
  items: T[],
  sort: string,
): T[] {
  return [...items].sort((a, b) => {
    switch (sort) {
      case 'newest': {
        const diff = new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime();
        return diff !== 0 ? diff : idDesc(a, b);
      }
      case 'oldest': {
        const diff = new Date(a.createdAt).getTime() - new Date(b.createdAt).getTime();
        return diff !== 0 ? diff : idDesc(a, b);
      }
      case 'severity': {
        const sa = SEVERITY_ORDER[a.severity ?? 'info'] ?? 3;
        const sb = SEVERITY_ORDER[b.severity ?? 'info'] ?? 3;
        if (sa !== sb) return sa - sb;
        const diff = new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime();
        return diff !== 0 ? diff : idDesc(a, b);
      }
      case 'attention_first':
      default: {
        const oa = STATUS_ORDER[a.status] ?? 5;
        const ob = STATUS_ORDER[b.status] ?? 5;
        if (oa !== ob) return oa - ob;
        const sa = SEVERITY_ORDER[a.severity ?? 'info'] ?? 3;
        const sb = SEVERITY_ORDER[b.severity ?? 'info'] ?? 3;
        if (sa !== sb) return sa - sb;
        const diff = new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime();
        return diff !== 0 ? diff : idDesc(a, b);
      }
    }
  });
}
